on:
  push:
    tags:
      - "v*"

name: Build and push docker containers

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_PACKAGES }}

      - name: Get tag
        id: source_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Push and build server
        uses: docker/build-push-action@v5
        with:
          push: true
          file: server/backend/Dockerfile
          context: server/backend/
          tags: |
            ghcr.io/sleipner42/gptfridge:${{ steps.source_tag.outputs.tag }}
            ghcr.io/sleipner42/gptfridge:latest
          labels: |
            org.opencontainers.image.source=https://github.com/sleipner42/gptfridge
